#+TITLE: Traveling Interesting places
#+DESCRIPTION:
#+KEYWORDS:
#+STARTUP:  content


- [[wiki:index][Index]]

- Parent: [[wiki:Traveling][Traveling]]

- Related: 

* Traveling. Interesting places

** Интересные локации для кемпинга
*** Беларусь
- Вилейское водохранилище, N1
  Координаты: 54.449739,27.169341
- Вилейское водохранилище, N2
  Координаты: 54.858605,26.900057
- Брестская область, N1
  Координаты: 52.426471,25.140940
- Кромань
  (КРОМАНЬ) озеро в Столбцовском р-не. Площадь 0,94 км.кв. Длина 1,2
  км. Максимаьная ширина 1,1 км. Расположено в бассейне реки Неман (Нёман), за
  38 км на северо-запад от Столбцов, в южной части Налибокской пущи (Налібоцкай
  пушчы). Склоны котловины пологие, поросшие лесом. Вдоль берегов
  зарастает. Впадают река Блюшка и мелиоративный канал, вытекает река
  Кроманка. Там рыболовная туристическая база, но если попросить уединенное
  место, то определят на дальний подход, а там никого не будет. Хорошее дно,
  отличная рыбалка, красивый лес до самой воды(не лесопосадка), много зверья
  любопытного)), Я был там месяц назад, для отдыха прекрасное место. Координаты:
  53.711339, 26.312027
- Смолевичский район, въезд в лес
  Координаты: 54.167772,28.183267
- Карта с интересными точками
  https://orda.of.by/.map/?52.161418,26.019774&m=osm/10
- Карьер в Заславле
  Координаты: 53.99679 27.24904
